config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :feeds do
    collection do
      post 'confirm'
    end
  end
end

app/models/abc.rb
module Abc
  def self.table_name_prefix
    'abc_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  # Feedモデルのimageカラムに、ImageUploaderを紐付けます。
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :text, presence: true, length: { maximum: 255 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: true
  
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :feeds, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # 全コントローラでモジュールを使用できるようにする
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all.order(id: "DESC")
  end

  def new
    # confirm.html.erbから戻るを押した時にbackが属性として付いてくる
    # 確認画面から戻った時の処理
    if params[:back]
      # 戻った際に送られたパラメーターをセットして新規画面を作成
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def edit
  end

  def create
    @feed = current_user.feeds.build(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to feeds_path, notice: '投稿しました' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to user_path(current_user.id), notice: '編集しました' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
  # idをもとにデータベースから該当するデータを取得する処理を記述
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :text, :image_cache, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # sessions/new/html.erbで入力されたemailが正しいかどうか
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログインしたユーザのidをセッションに保存
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = "ログインに失敗しました"   
      redirect_to "/"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # new.html.erbから受け取ったパラメーターでインスタンスを作成
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    # new.html.erbからパラメーターを受ける
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_feeds_path
    elsif action_name == "edit"
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    # sessions_controller.rbでログインユーザのidをセッションに保存
    # 保存したセッションを元にログインユーザのレコードを取得し@current_userに代入
    # ||=によって、既にログイン済みのユーザーはそのままとなる
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザがログインしていればtrue、そうで無いならfalseを返す
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "件") %> のエラーがあります。</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field-image">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :feed_text %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= form.label :image %>
  <%= image_tag(@feed.image.url) if @feed.image.url %>
  <%= form.hidden_field :image_cache %>

  <div class="field">
    <%= form.label :text %>
    <%= form.hidden_field :text %>
    <%= @feed.text %>
  </div>
  
  <div class="actions">
    <%= form.submit "投稿する", class: "btn btn-primary" %>
  </div>
<% end %>

<%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :text %>
  <%= form.submit "戻る", name: "back",class: "btn btn-primary back-button",role: "button" %>
<% end %>

app/views/feeds/edit.html.erb
<h1>編集</h1>
<%= render 'form', feed: @feed %>
<%= link_to '戻る', user_path(current_user.id), class: "btn btn-primary back-button",role: "button" %>

app/views/feeds/index.html.erb
<div class="main-content">
  <h1>タイムライン</h1>
  <% @feeds.each do |feed| %>
    <div class="card" >
      <div class="card-body">
        <p class="card-user"><%= feed.user.name %></p>
        <span><%= feed.created_at.strftime("%m月%d日%H:%M") %></span>
        <p class="card-text"><%= feed.text %></p>         
      </div>
    <%= image_tag feed.image.url, class: "card-img-bottom" %>
    </div>
  <% end %>
</div>

app/views/feeds/new.html.erb
<h1>新規投稿</h1>
<%# _form.html.erbにfeedで値を渡す　@feed=Feed.new %>
<%= render 'form', feed: @feed %>
<%= link_to '戻る', feeds_path,class: "btn btn-primary back-button",role: "button" %>

app/views/layouts/_form.html.erb
<% if logged_in? %>
  <%= link_to "Profile", user_path(current_user.id) %>
  <%= link_to "Logout", session_path(current_user.id), method: :delete %>
  <%= link_to "Post", new_feed_path %>
  <%= link_to "PostIndex", feeds_path %>
<% else %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- 画面サイズが小さい時に表示されるボタン -->
        <!-- data-targetにollapseを指定したdivのidを指定すること -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-id">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">FacebookClone</a>
      </div>
      <!-- idは、上記ボタンのdata-targetに指定したものと揃えること -->
      <div class="collapse navbar-collapse" id="collapse-id">
        <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %>

          <table class="login-table">
            <tbody>
              <tr>
                <td><%= f.label :email %></td>
                <td><%= f.label :password %></td>
              </tr>
              <tr>
                <td><%= f.email_field :email %></td>
                <td><%= f.password_field :password %></td>
                <td><%= f.submit "ログイン" %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>   
<% end %>   

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- 画面サイズが小さい時に表示されるボタン -->
        <!-- data-targetにollapseを指定したdivのidを指定すること -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-id">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/feeds">FacebookClone</a>
        <p class="navbar-text navbar-right"><%= current_user.name %>でログイン中</p>
        <div class="collapse navbar-collapse" id="collapse-id">
          <div class="side-in-header">
            <ul class="list-in-header">
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li><%= link_to "投稿する", new_feed_path %></li>
              <li><%= link_to "タイムライン", feeds_path %></li>
              <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- 画面サイズが小さい時に表示されるボタン -->
        <!-- data-targetにollapseを指定したdivのidを指定すること -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-id">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">FacebookClone</a>
      </div>
      <!-- idは、上記ボタンのdata-targetに指定したものと揃えること -->
      <div class="collapse navbar-collapse" id="collapse-id">
        <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %>
          <table class="login-table">
            <tbody>
              <tr>
                <td><%= f.label :email %></td>
                <td><%= f.label :password %></td>
              </tr>
              <tr>
                <td><%= f.email_field :email %></td>
                <td><%= f.password_field :password %></td>
                <td><%= f.submit "ログイン" %></td>
              </tr>
            </tbody>
          </table>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>   
<% end %>   

app/views/layouts/_sidebar.html.erb
<% if logged_in? %>
  <div class="side">
    <ul class="list">
      <li><%= link_to "マイページ", user_path(current_user.id) %></li>
      <li><%= link_to "投稿する", new_feed_path %></li>
      <li><%= link_to "タイムライン", feeds_path %></li>
      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <%= render 'layouts/sidebar'  %>

    <% flash.each do |key, value| %>
        <% key = "info" if key == "notice" %>
        <% key = "danger" if key == "alert" %>
        <%= content_tag(:div, value, class: "alert alert-success alert-#{key}" ,role: "alert") %>
    <% end %>

    <div class="content">
      <%= yield %>
    </div>
    
    <footer>
      <p>運営会社フッターだよ株式会社</p>
    </footer>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<a href="/"><img src="/assets/images.png"></a>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <%= image_tag 'face.jpg', class: "col-md-6" %>
    <%= form_with(model: @user, local: true, class: "col-md-6 signup-form") do |f| %> 
      <% if @user.errors.any? %>
        <div class="alert alert-warning">
          <h2><%= pluralize(@user.errors.count, "件") %> のエラーがあります。</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <h1>新規アカウントを作成</h1>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">      
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      </div>  

      <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <%= f.submit "アカウント登録" ,class: "create-account-button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if @user.feeds.empty? %> 
  <p>投稿はありません</p>
<% else %>
      <%# user_idからfeedテーブルのレコードを取得し一つずつuserに入れる %>
      <%# feedにはfeedのレコードが入っている%>
  <% @user.feeds.order(id: "DESC").each do |feed| %>
    <div class="card" >
      <div class="card-body">
        <span><%= feed.created_at.strftime("%m月%d日%H:%M") %></span>
        <p class="card-text"><%= feed.text %></p>         
      </div>
      <%= image_tag feed.image.url, class: "card-img-bottom" %>   
      <%= link_to '編集する', edit_feed_path(feed.id) %>
      <%= link_to '削除する', feed_path(feed.id), method: :delete, data: { confirm: 'Are you sure?' } %>
     </div>
  <% end %>
<% end %>